AllCops:
  DisplayCopNames: true

#
# Style
#

LineLength:
  Max: 128

Style/StringLiterals:
  EnforcedStyle: double_quotes

#
# Metrics
#

Metrics/ClassLength:
  Max: 100

Metrics/MethodLength:
  Max: 25
