language: ruby
sudo: false
dist: trusty
cache: bundler

matrix:
  include:
    - rvm: 2.3
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: jruby-head
    - name: truffleruby
      rvm: system
      install:
        - export TRUFFLERUBY_VERSION=1.0.0-rc9
        - curl -L https://github.com/oracle/truffleruby/releases/download/vm-$TRUFFLERUBY_VERSION/truffleruby-$TRUFFLERUBY_VERSION-linux-amd64.tar.gz | tar xz
        - export PATH="$PWD/truffleruby-$TRUFFLERUBY_VERSION-linux-amd64/bin:$PATH"
        - $PWD/truffleruby-$TRUFFLERUBY_VERSION-linux-amd64/lib/truffle/post_install_hook.sh
        - gem install bundler
        - bundle install
    - rvm: ruby-head
    - rvm: rbx-3
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3
    - rvm: truffleruby
